// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Operation struct {
	ID            pgtype.UUID      `json:"id"`
	WalletID      pgtype.UUID      `json:"wallet_id"`
	OperationType string           `json:"operation_type"`
	Amount        int32            `json:"amount"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Wallet struct {
	ID        pgtype.UUID      `json:"id"`
	Balance   int32            `json:"balance"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
