name: "javacode-wallet"

services:
  wallet-server:
    build:
      context: .
    image: wallet-server:latest
    container_name: wallet-server
    environment:
      - DB_URL=postgres://javacode:secret@postgres:5432/wallet
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    container_name: wallet-postgres
    environment:
      POSTGRES_USER: javacode
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: wallet
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U javacode -d wallet"]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
